### ISSUE TITLE
Throws RangeError

### ISSUE THREAD

**Issue by davisskchan** [raml-org/ramldt2jsonschema#10]
[eeEntityLib.v1.0.txt](https://github.com/raml-org/ramldt2jsonschema/files/586626/eeEntityLib.v1.0.txt)

E:\Projects\atom\Brooklyn\EE\schemas>dt2js eeEntityLib.v1.0.raml identityEntity
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.cljs$core$quote_string [as quote_string] (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:30659:45)
    at Object.cljs$core$pr_writer_impl [as pr_writer_impl] (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:30717:42)
    at cljs$core$pr_writer (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:30792:18)
    at C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:31216:142
    at Object.cljs$core$pr_sequential_writer [as pr_sequential_writer] (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:30522:142)
    at Object.cljs$core$print_map [as print_map] (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:31212:18)
    at cljs.core.PersistentHashMap.cljs$core$IPrintWithWriter$_pr_writer$arity$3 (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:31334:18)
    at Object.cljs$core$pr_str_STAR_ [as pr_str_STAR_] (C:\Users\DavisChan\AppData\Roaming\npm\node_modules\ramldt2jsonschema\node_modules\datatype-expansion\node\cljs\core.js:3164:5)

**Comment by jstoiko** [comment]
hi @davisskchan, the issue is with:
```
meta: cs.csIdentityMetaEntity
```
if I remove that line, it works.

as highlighted in a [previous issue](https://github.com/raml-org/ramldt2jsonschema/issues/9), `dt2js` does not support external includes. It won't fail if there are includes in the RAML file, but it will fail if the type passed to `dt2js` contains a reference to an external include.

**Comment by postatum** [comment]
External includes will be supported in a new major version.
